// <auto-generated />
using System;
using BonAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BonAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BonAPI.Models.Bon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<double>("Off")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Bons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = 1001,
                            Created = new DateTime(2024, 2, 23, 0, 36, 49, 722, DateTimeKind.Local).AddTicks(3488),
                            Off = 10.0
                        },
                        new
                        {
                            Id = 2,
                            Code = 1002,
                            Created = new DateTime(2024, 2, 23, 0, 36, 49, 722, DateTimeKind.Local).AddTicks(3537),
                            Off = 20.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
